# -*- coding: utf-8 -*-
{
    'name': u'Hill Top ERP',
    'version': '14.0e',
    'category': 'Hill Top ERP',
    'summary': '',
    'website': 'https://silentinfotech.com',
    'description': u"""


This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.

""",
    'author': u'Hill Top ERP',
    'depends': ['product','base','stock','purchase','sale'],

    'data': [
        # 'security/ir.model.access.csv',
        'views/stock_move_line_view.xml',
        'views/stock_quant_view.xml',
    ],
    'qweb': [

    ],

    'application': False,
    'license': u'OPL-1',
    'auto_install': False,
    'installable': True,
}
